---
apt_autorestart_services: false
apt_unattended_upgrades: false
apt_unattended_upgrades_exclude_packages: []
apt__unattended_upgrades_reboot: false
apt__upgrade_time: "23:30"
apt__update_time: "22:30"
