---
qlcplus__display: HDMI-A-1
qlcplus__working_dir: /home/wal/light
qlcplus__startup_command: /bin/bash -c "git -c safe.directory={{ qlcplus__working_dir }} pull || echo 'Git pull failed'; /usr/bin/qlcplus --open wal.qxw --web --web-port 80 --fullscreen normal --operate"
qlcplus__resolution: 1024x600
qlcplus__user: wal
qlcplus__repo: https://github.com/23wal/light.git
